version: '3.9'

services:
  main:
    container_name: codica-test-task
    build:
      context: .
      target: development
      dockerfile: ./.docker/node/Dockerfile
    volumes:
      - .:/usr/codicatest/app
      - /usr/codicatest/app/node_modules
    command: npm run start:debug
    env_file:
      - .env
    depends_on:
      - codica-postgres
  postgres:
    container_name: codica-postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
